/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed-dim": "#fcbc0b",
        "on-secondary-container": "#636262",
        "secondary-container": "#e2dfde",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e4e2e2",
        "on-background": "#1b1c1c",
        "inverse-on-surface": "#f2f0f0",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c6c6c7",
        "background": "#fbf9f8",
        "surface-container-highest": "#e4e2e2",
        "surface-container-low": "#f5f3f3",
        "primary-container": "#febe10",
        "on-primary-fixed-variant": "#5c4300",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container": "#efeded",
        "on-primary-container": "#6c4f00",
        "surface-dim": "#dbdad9",
        "surface": "#fbf9f8",
        "inverse-surface": "#303031",
        "primary": "#7a5900",
        "secondary": "#5f5e5e",
        "tertiary-container": "#c8c8c8",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdea1",
        "on-surface-variant": "#504532",
        "on-error": "#ffffff",
        "outline": "#827560",
        "on-tertiary": "#ffffff",
        "tertiary": "#5d5f5f",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#525454",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-surface": "#1b1c1c",
        "on-secondary": "#ffffff",
        "outline-variant": "#d4c5ac",
        "surface-tint": "#7a5900",
        "on-tertiary-fixed-variant": "#454747",
        "tertiary-fixed": "#e2e2e2",
        "inverse-primary": "#fcbc0b",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#261900",
        "on-secondary-fixed-variant": "#474746",
        "surface-bright": "#fbf9f8",
        "surface-container-high": "#e9e8e7",
        "night-black": "#1A1A1A",
        "madrid-gold": "#FEBE10"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "16px",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "lg": "24px",
        "md": "16px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "sm": "8px",
        "margin-desktop": "40px",
        "xl": "32px",
        "base": "8px",
        "2xl": "48px",
        "3xl": "64px"
      },
      "fontFamily": {
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "metric-lg": ["Inter", "sans-serif"],
        "metric-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "metric-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "800"}],
        "metric-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
