version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cybersense_db
    restart: always
    environment:
      POSTGRES_DB: cybersense
      POSTGRES_USER: cybersense_admin
      POSTGRES_PASSWORD: cybersense_secure_pass_2026
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cybersense_admin -d cybersense"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cybersense_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cybersense_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://cybersense_admin:cybersense_secure_pass_2026@db:5432/cybersense
      - JWT_SECRET=9s8dfyhsdf987ysd9f87ysd9f87ysd98f7ysd9f87ysdfhskjdhfksjdhf
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - ENVIRONMENT=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ML_SERVICE_URL=http://ml:8080
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      db:
        condition: service_healthy
      ml:
        condition: service_started
      kafka:
        condition: service_started
    volumes:
      - ml_models:/app/app/ml/models
    networks:
      - cybersense_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: cybersense_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    networks:
      - cybersense_network

  ml:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    container_name: cybersense_ml
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ml_models:/app/app/models
    networks:
      - cybersense_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cybersense_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cybersense_network

volumes:
  pgdata:
  ml_models:

networks:
  cybersense_network:
    driver: bridge
