version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cybersense_db
    restart: always
    environment:
      POSTGRES_DB: cybersense
      POSTGRES_USER: cybersense_admin
      POSTGRES_PASSWORD: cybersense_secure_pass_2026
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cybersense_admin -d cybersense"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cybersense_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cybersense_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://cybersense_admin:cybersense_secure_pass_2026@db:5432/cybersense
      - JWT_SECRET=9s8dfyhsdf987ysd9f87ysd9f87ysd98f7ysd9f87ysdfhskjdhfksjdhf
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - ENVIRONMENT=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ML_SERVICE_URL=http://ml:8080
    depends_on:
      db:
        condition: service_healthy
      ml:
        condition: service_started
    volumes:
      - ml_models:/app/app/ml/models
    networks:
      - cybersense_network

  ml:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    container_name: cybersense_ml
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ml_models:/app/app/models
    networks:
      - cybersense_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cybersense_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cybersense_network

volumes:
  pgdata:
  ml_models:

networks:
  cybersense_network:
    driver: bridge
